@vantagePMO_platform_HostAddress = http://localhost:5278

### Sign up (creates user + profile)
POST {{vantagePMO_platform_HostAddress}}/api/v1/authentication/sign-up
Content-Type: application/json
Accept-Language: es

{
  "fullName": "Alex Sterling",
  "username": "alex.sterling",
  "role": "Project Manager",
  "dateOfBirth": "15/03/1990",
  "email": "alex.sterling@vantagepmo.io",
  "password": "Secret123!",
  "confirmPassword": "Secret123!"
}

### Sign in (200 OK, 400 if invalid credentials)
POST {{vantagePMO_platform_HostAddress}}/api/v1/authentication/sign-in
Content-Type: application/json

{
  "username": "alex.sterling",
  "password": "Secret123!"
}

### Get a profile by id (200 OK, 404 if not found)
GET {{vantagePMO_platform_HostAddress}}/api/v1/profiles/1
Accept: application/json

### Get a profile by email (200 OK, 400 if missing param, 404 if not found)
GET {{vantagePMO_platform_HostAddress}}/api/v1/profiles?email=alex.sterling@vantagepmo.io
Accept: application/json

### Partially update a profile (200 OK, 404 if not found, 409 if email duplicated)
PATCH {{vantagePMO_platform_HostAddress}}/api/v1/profiles/1
Content-Type: application/json

{
  "role": "Senior Project Manager",
  "availabilityLabel": "Fully Booked"
}

###
