// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VantagePMO_platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace VantagePMO_platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("vantagePMO_platform.Analytics.Domain.Model.Aggregates.AnalyticsDashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("MonthlyExpenditures")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("monthly_expenditures");

                    b.Property<string>("PortfolioRoi")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("portfolio_roi");

                    b.Property<string>("ResourceSaturation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("resource_saturation");

                    b.Property<string>("SummaryKpis")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("summary_kpis");

                    b.Property<string>("TopMovers")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("top_movers");

                    b.HasKey("Id")
                        .HasName("p_k_analytics");

                    b.ToTable("analytics", (string)null);
                });

            modelBuilder.Entity("vantagePMO_platform.ChatHub.Domain.Model.Aggregates.Chat", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsFavorited")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_favorited");

                    b.Property<string>("Members")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("members");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_chats");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("vantagePMO_platform.ChatHub.Domain.Model.Aggregates.ChatInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("chat_id");

                    b.Property<string>("Insights")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("insights");

                    b.Property<string>("MeetingTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("meeting_tag");

                    b.Property<string>("MeetingTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("meeting_title");

                    b.Property<int>("SentimentProductive")
                        .HasColumnType("int")
                        .HasColumnName("sentiment_productive");

                    b.Property<string>("SentimentText")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sentiment_text");

                    b.Property<string>("TimeAgo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("time_ago");

                    b.HasKey("Id")
                        .HasName("p_k_chat_insights");

                    b.ToTable("chat_insights", (string)null);
                });

            modelBuilder.Entity("vantagePMO_platform.ChatHub.Domain.Model.Aggregates.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("attachments");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("author_id");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("chat_id");

                    b.Property<string>("Reactions")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reactions");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("text");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("p_k_chat_messages");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("vantagePMO_platform.ChatHub.Domain.Model.Aggregates.ChatPinnedAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("chat_id");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("meta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_chat_pinned_assets");

                    b.ToTable("chat_pinned_assets", (string)null);
                });

            modelBuilder.Entity("vantagePMO_platform.ChatHub.Domain.Model.Aggregates.ChatUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar");

                    b.Property<string>("AvatarSeed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("avatar_seed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_chat_users");

                    b.ToTable("chat_users", (string)null);
                });

            modelBuilder.Entity("vantagePMO_platform.Meetings.Domain.Model.Aggregates.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Agreements")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("agreements");

                    b.Property<string>("Attendees")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("attendees");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("duration");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("location");

                    b.Property<string>("Minutes")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("minutes");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("organizer");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("segment");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time")
                        .HasColumnName("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_meetings");

                    b.ToTable("meetings", (string)null);
                });

            modelBuilder.Entity("VantagePMO_platform.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ActiveBudget")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("active_budget");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("availability");

                    b.Property<string>("AvailabilityLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("availability_label");

                    b.Property<string>("AvatarSeed")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("avatar_seed");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bio");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("certifications");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryRate")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("delivery_rate");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("email");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("experience");

                    b.Property<string>("Joined")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("joined");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("role");

                    b.Property<string>("SkillsDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("skills_description");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearsActive")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("years_active");

                    b.HasKey("Id")
                        .HasName("p_k_profiles");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_profiles_email");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("vantagePMO_platform.Reports.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ActiveRisks")
                        .HasColumnType("int")
                        .HasColumnName("active_risks");

                    b.Property<double>("AggregateHealth")
                        .HasColumnType("double")
                        .HasColumnName("aggregate_health");

                    b.Property<string>("AiInsight")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("ai_insight");

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("attachment");

                    b.Property<int>("Automations")
                        .HasColumnType("int")
                        .HasColumnName("automations");

                    b.Property<double>("BudgetVariance")
                        .HasColumnType("double")
                        .HasColumnName("budget_variance");

                    b.Property<int>("Completion")
                        .HasColumnType("int")
                        .HasColumnName("completion");

                    b.Property<int>("CriticalRisks")
                        .HasColumnType("int")
                        .HasColumnName("critical_risks");

                    b.Property<int>("EnergyConsumption")
                        .HasColumnType("int")
                        .HasColumnName("energy_consumption");

                    b.Property<string>("GeneratedAt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("generated_at");

                    b.Property<double>("HealthTrend")
                        .HasColumnType("double")
                        .HasColumnName("health_trend");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("label");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("manager");

                    b.Property<int>("MinorRisks")
                        .HasColumnType("int")
                        .HasColumnName("minor_risks");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("period");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("project");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("type");

                    b.Property<string>("VelocityTrend")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("velocity_trend");

                    b.HasKey("Id")
                        .HasName("p_k_reports");

                    b.ToTable("reports", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
